#!/usr/bin/env bash
# Install a `gflib-build` launcher on your PATH so you can run the Rust port from ANY directory while
# it always uses the SAME config + data dir (this repo's gflib-data/). Idempotent: re-run to refresh.
#
#   rust/install-cli.sh                 # installs to ~/.local/bin/gflib-build
#   rust/install-cli.sh /usr/local/bin  # or any directory already on your PATH (may need sudo)
#
# After installing, just type:  gflib-build            (live TUI on the shared build dir)
#                               gflib-build --only ofl/abel
#                               gflib-build --attach    (monitor a running build)
#                               gflib-build --stop      (cancel the build)
# Extra args are forwarded verbatim, so any one-off flag still works.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"     # the gflib-build repo root (absolute → CWD-independent)
RUST="$REPO/rust/target/release/gflib-build"
BINDIR="${1:-$HOME/.local/bin}"
WRAPPER="$BINDIR/gflib-build"

if [ ! -x "$RUST" ]; then
  echo "!! $RUST not built yet. Build it first:"
  echo "     (cd $REPO/rust && cargo build --release)"
  exit 1
fi

mkdir -p "$BINDIR"

# The wrapper bakes in ABSOLUTE repo paths, so the same config/data dir is used no matter where you
# call it from. Defaults mirror run-on-host.sh; all are overridable by passing the same flag again
# (later flags win), and any extra args ("$@") are appended.
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by gflib-build/rust/install-cli.sh — launches the Rust port with this machine's
# canonical config/data dir regardless of the current working directory. Re-run install-cli.sh to
# regenerate after moving the repo.
exec "$RUST" \\
  --data-dir "$REPO/gflib-data" \\
  --build-dir "$REPO/gflib-data/build" \\
  --source metadata \\
  --google-fonts "$REPO/gflib-data/google-fonts" \\
  --archive "$REPO/gflib-data/archive" \\
  --manage-venvs \\
  --base-requirements "$REPO/requirements-build.txt" \\
  --base-python python3 \\
  "\$@"
EOF
chmod +x "$WRAPPER"

echo "installed: $WRAPPER  ->  $RUST"
echo "          (always uses --data-dir $REPO/gflib-data)"
case ":$PATH:" in
  *":$BINDIR:"*) echo "ok: $BINDIR is on your PATH — just type 'gflib-build'." ;;
  *) echo "note: $BINDIR is NOT on your PATH. Add this to your shell rc:"
     echo "        export PATH=\"$BINDIR:\$PATH\"" ;;
esac
